[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[google-chrome]
source = "cmd"
cmd = '''wget -qO- http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/other.xml.gz | zgrep -A1 "google-chrome-stable" | awk -F\" '/version/ {print $4"-"$6}' '''

[fbcat]
source = "aur"

[winterpy]
source = "github"
github = "lilydjwg/winterpy"

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"

[ssed]
source = "regex"
regex = "The current version is ([\\d.]+)\\."
url = "https://sed.sourceforge.net/grabbag/ssed/"
proxy = "http://localhost:8087"

[PySide]
source = "pypi"
pypi = "nvchecker"

[test]
source = "manual"
manual = "0.1"
